# Generated by Django 4.2 on 2024-05-05 16:17

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchase_orders",
            "0003_alter_purchaseorder_buyer_alter_purchaseorder_vendor",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.DecimalValidator(
                                decimal_places=1, max_digits=16
                            ),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="items",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="items",
            field=models.ManyToManyField(
                related_name="items", to="purchase_orders.item"
            ),
        ),
    ]
